export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SET_ALL_PHOTOS: "SET_ALL_PHOTOS",
  SET_ALBUMS: "SET_ALBUMS",
  SELECTED_PHOTO:"SELECTED_PHOTO"
};
